export const english = {
  title: 'Small story labs',
  storyTitle: 'The quiet room',
  kitchenTitle: 'The turn workshop',
  storyLink: 'Story room',
  kitchenLink: 'Turn workshop',
  pause: 'Pause',
  resume: 'Resume',
  replay: 'Replay voice sample',
  settings: 'Settings',
  help: 'Help',
  helpText: 'Select a button. Nothing needs dragging or quick reactions.',
  close: 'Close',
  save: 'Save',
  retry: 'Retry save',
  load: 'Resume saved progress',
  export: 'Export local backup',
  import: 'Import local backup',
  reset: 'Reset this profile',
  confirmReset: 'Confirm reset',
  cancel: 'Cancel',
  resetWarning: 'This removes this lab profile only. Export a backup first.',
  storageIdle: 'No save yet.',
  storagePending: 'Saving…',
  storageSaved: 'Saved locally.',
  pendingAction:
    'The accepted action still has turns to finish. Resume or retry; do not repeat it.',
  preferencesFailure: 'The view preference is applied but not saved. Retry saving settings.',
  storageFailure: 'Saving is blocked. Progress is not safely saved. Retry or import a backup.',
  storageConflict:
    'Another tab saved first. Close this tab or deliberately reload the saved profile.',
  error: 'That action is unavailable. Review the current state or try again.',
  startupFailure:
    'The lab could not open. Saved progress was not replaced. Check content, storage or backup compatibility before retrying.',
  retryOpen: 'Retry opening',
  recoveryTitle: 'Recover local progress',
  recoveryNotice:
    'The original record is unchanged. Export it before replacing progress. Import a compatible backup or explicitly reset this profile.',
  recoveryFailed:
    'Recovery was refused. The original record is unchanged; check compatibility or retry storage.',
  recoveryImport: 'Validate and replace from selected backup',
  recoveryPrevious: 'Validate and restore the previous revision',
  offline: 'Install for offline use',
  offlineReady: 'This pack is installed for offline use.',
  offlineMissing: 'Offline pack is not installed.',
  offlineInstalling: 'Installing the complete offline pack…',
  offlineFailed: 'Offline installation failed. The pack is not ready.',
  offlineScope: 'Installation needs a connection. Browser storage may be cleared; keep backups.',
  voiceMissing: 'Voice samples are unavailable. Captions remain readable.',
  voiceScope: 'Only three sample lines have recordings, not complete narration.',
  audioBlocked: 'Activate replay to unlock sound.',
  audioFailed: 'Sound is unavailable; read the caption.',
  language: 'Language',
  russian: 'Русский',
  english: 'English',
  largeText: 'Double text size',
  comfort: 'Brighter comfort palette',
  reducedMotion: 'Reduce motion',
  narrationVolume: 'Narration volume',
  musicVolume: 'Music volume',
  effectsVolume: 'Effects volume',
  spoiler: 'Hide private or spoiler details',
  name: 'Local display name',
  setName: 'Save name',
  scarf: 'Wear the scarf',
  avatar: 'Layered avatar',
  roomImage: 'A bright room with a table, window and shelf.',
  map: 'Map',
  roomLocation: 'Return to the room',
  mapText: 'One room connects to a quiet garden.',
  welcome: 'Welcome. You can try different tasks at your pace.',
  'lab.welcome': 'Welcome. You can try different tasks at your pace.',
  'lab.clue': 'Read the clue. It can help you find the next step.',
  'lab.complete': 'Well done! The tasks are finished. You can try again.',
  look: 'Explore the room',
  talk: 'Ask for advice',
  tip: 'Find the note, match the shapes, then arrange the day.',
  back: 'Return',
  room: 'Find three clues. Their meanings belong in your notebook.',
  finish: 'Finish together',
  complete: 'Well done! A scarf is yours, only once.',
  scene: 'Find the note',
  matching: 'Match two shapes',
  ordering: 'Arrange the day',
  note: 'Note on the table',
  window: 'Window',
  drop: 'Blue drop',
  'drop.explanation': 'The blue drop is decoration, not evidence.',
  round: 'Round shape',
  sun: 'Sun',
  leaf: 'Leaf',
  card: 'Shape card',
  morning: 'Morning',
  day: 'Day',
  evening: 'Evening',
  submit: 'Check the order',
  clear: 'Clear selection',
  notebook: 'Notebook',
  dialogue: 'Dialogue',
  extras: 'Generated and print fixtures',
  axis: 'Notebook category',
  hint: 'Explain a clue',
  'hint.explained': 'The note was on the table. This rules out the shelf.',
  'clue.place': 'The note was on the table.',
  'clue.shape': 'The matching shape is the sun.',
  'clue.time': 'The sequence starts in the morning.',
  shape: 'Shape',
  place: 'Place',
  time: 'Time',
  table: 'Table',
  shelf: 'Shelf',
  confirmed: 'Confirmed',
  excluded: 'Excluded',
  unknown: 'Unknown',
  candidates: 'Remaining possibilities: {count}',
  completed: 'Completed',
  progress: 'Progress',
  family: 'Two-player handoff',
  'player.first': 'First player',
  'player.second': 'Second player',
  handoff: 'Pass the device. Private cards are hidden.',
  confirmPlayer: 'I am ready',
  nextPlayer: 'Pass to the other player',
  'private.first': 'My card shows a quiet window.',
  'private.second': 'My card shows a small garden.',
  privacyVeil: 'Confirm before showing this private view.',
  begin: 'Open the workshop',
  wait: 'Wait two turns',
  listen: 'Listen to the maker: one turn',
  startA: 'Start batch A',
  startB: 'Start batch B',
  nextPhase: 'Enter the rest phase',
  finishShare: 'Share the result',
  finishKeep: 'Keep the result',
  purchase: 'Buy a sample: no turn cost',
  budget: 'Add one turn to the allowance',
  slots: 'Shelf slots',
  slot: 'Slot {number}: {item}, age {age}',
  empty: 'empty',
  'aegis.browser.select-item': 'Select an item first.',
  occupied: 'The destination is occupied.',
  selected: 'Selected: {item}. Choose an empty slot.',
  cancelSelection: 'Cancel selection',
  turns: 'Logical turn: {turn}. Remaining allowance: {remaining}.',
  produced: 'Completed batches: {count}',
  credit: 'Credit: {count}',
  phase: 'Phase: {phase}',
  setup: 'setup',
  workshop: 'workshop',
  rest: 'rest',
  ready: 'ready',
  working: 'working',
  waiting: 'waiting',
  incoming: 'not yet arrived',
  gone: 'left',
  reader: 'Reader',
  maker: 'Maker',
  visitor: 'Visitor',
  'batch-a': 'Batch A',
  'batch-b': 'Batch B',
  shared: 'Shared ending',
  kept: 'Kept ending',
  reloadConfig: 'Validate edited balance for a new run',
  reloadWarning: 'Reload starts a new run only after complete validation. Back up first.',
  balanceReady: 'New balance is active in a fresh run.',
  ruleOrder: 'Same-turn order: batches, arrival, expiration.',
  status: 'Status',
  ambience: 'Enable gentle pulse fixture',
  silence: 'Silence',
  print: 'Print sample',
  generated: 'Generated fixture',
  printScope: 'Small approved content samples, not a complete printed game.',
};

export const russian: Record<keyof typeof english, string> = {
  title: 'Маленькие истории',
  storyTitle: 'Тихая комната',
  kitchenTitle: 'Мастерская ходов',
  storyLink: 'Комната историй',
  kitchenLink: 'Мастерская ходов',
  pause: 'Пауза',
  resume: 'Продолжить',
  replay: 'Повторить голосовой образец',
  settings: 'Настройки',
  help: 'Помощь',
  helpText: 'Выбирай кнопки. Перетаскивание и быстрые реакции не нужны.',
  close: 'Закрыть',
  save: 'Сохранить',
  retry: 'Повторить сохранение',
  load: 'Вернуть сохранённое',
  export: 'Скачать местную копию',
  import: 'Загрузить местную копию',
  reset: 'Сбросить этот профиль',
  confirmReset: 'Подтвердить сброс',
  cancel: 'Отмена',
  resetWarning: 'Исчезнет только этот профиль лаборатории. Сначала скачай копию.',
  storageIdle: 'Сохранений пока нет.',
  storagePending: 'Сохраняем…',
  storageSaved: 'Сохранено на устройстве.',
  pendingAction:
    'У принятого действия остались ходы. Продолжи или повтори сохранение, но не действие.',
  preferencesFailure: 'Настройка вида применена, но не сохранена. Повтори сохранение настроек.',
  storageFailure: 'Сохранение заблокировано. Прогресс пока не сохранён надёжно. Повтори попытку.',
  storageConflict: 'Другая вкладка сохранила раньше. Закрой эту или верни сохранённое.',
  error: 'Это действие пока недоступно. Проверь состояние или попробуй снова.',
  startupFailure:
    'Лаборатория не открылась. Сохранённый прогресс не заменён. Проверь данные, хранилище или совместимость копии.',
  retryOpen: 'Попробовать открыть снова',
  recoveryTitle: 'Восстановление местного прогресса',
  recoveryNotice:
    'Исходная запись не изменена. Сначала скачай её. Можно загрузить совместимую копию или явно сбросить этот профиль.',
  recoveryFailed:
    'Восстановление отклонено. Исходная запись сохранена; проверь совместимость или хранилище.',
  recoveryImport: 'Проверить и заменить выбранной копией',
  recoveryPrevious: 'Проверить и вернуть предыдущую копию',
  offline: 'Установить для игры без сети',
  offlineReady: 'Этот набор установлен для игры без сети.',
  offlineMissing: 'Набор для игры без сети не установлен.',
  offlineInstalling: 'Устанавливаем полный набор…',
  offlineFailed: 'Установка не удалась. Набор пока не готов.',
  offlineScope: 'Установка требует сети. Браузер может очистить хранилище; сохраняй копии.',
  voiceMissing: 'Голосовые образцы пока недоступны. Подписи остаются на экране.',
  voiceScope: 'Записаны только три образца, а не весь текст.',
  audioBlocked: 'Нажми повтор, чтобы разрешить звук.',
  audioFailed: 'Звук недоступен; прочитай подпись.',
  language: 'Язык',
  russian: 'Русский',
  english: 'English',
  largeText: 'Увеличить текст вдвое',
  comfort: 'Более светлая палитра',
  reducedMotion: 'Уменьшить движение',
  narrationVolume: 'Громкость голоса',
  musicVolume: 'Громкость музыки',
  effectsVolume: 'Громкость звуков',
  spoiler: 'Скрыть личные подробности и спойлеры',
  name: 'Имя только на устройстве',
  setName: 'Сохранить имя',
  scarf: 'Надеть шарф',
  avatar: 'Персонаж из слоёв',
  roomImage: 'Светлая комната: стол, окно и полка.',
  map: 'Карта',
  roomLocation: 'Вернуться в комнату',
  mapText: 'Из одной комнаты можно выйти в тихий сад.',
  welcome: 'Добро пожаловать. Здесь можно спокойно попробовать разные задания.',
  'lab.welcome': 'Добро пожаловать. Здесь можно спокойно попробовать разные задания.',
  'lab.clue': 'Посмотри на подсказку. Она поможет найти следующий шаг.',
  'lab.complete': 'Отлично! Все задания готовы. Ты можешь попробовать снова.',
  look: 'Осмотреть комнату',
  talk: 'Попросить совет',
  tip: 'Найди записку, соедини формы, затем расположи время суток.',
  back: 'Назад',
  room: 'Найди три подсказки. Запиши их смысл в блокнот.',
  finish: 'Завершить вместе',
  complete: 'Отлично! Тебе достаётся шарф, только один раз.',
  scene: 'Найди записку',
  matching: 'Соедини две формы',
  ordering: 'Расположи время суток',
  note: 'Записка на столе',
  window: 'Окно',
  drop: 'Синяя капля',
  'drop.explanation': 'Синяя капля — украшение, а не улика.',
  round: 'Круглая форма',
  sun: 'Солнце',
  leaf: 'Лист',
  card: 'Карточка формы',
  morning: 'Утро',
  day: 'День',
  evening: 'Вечер',
  submit: 'Проверить порядок',
  clear: 'Очистить выбор',
  notebook: 'Блокнот',
  dialogue: 'Разговор',
  extras: 'Примеры создания и печати',
  axis: 'Раздел блокнота',
  hint: 'Объяснить подсказку',
  'hint.explained': 'Записка лежала на столе. Значит, полка не подходит.',
  'clue.place': 'Записка лежала на столе.',
  'clue.shape': 'Подходящая форма — солнце.',
  'clue.time': 'Порядок начинается с утра.',
  shape: 'Форма',
  place: 'Место',
  time: 'Время',
  table: 'Стол',
  shelf: 'Полка',
  confirmed: 'Подтверждено',
  excluded: 'Исключено',
  unknown: 'Пока неизвестно',
  candidates: 'Осталось вариантов: {count}',
  completed: 'Готово',
  progress: 'Прогресс',
  family: 'Передача между двумя игроками',
  'player.first': 'Первый игрок',
  'player.second': 'Второй игрок',
  handoff: 'Передай устройство. Личные карточки скрыты.',
  confirmPlayer: 'Я готов',
  nextPlayer: 'Передать другому игроку',
  'private.first': 'На моей карточке тихое окно.',
  'private.second': 'На моей карточке маленький сад.',
  privacyVeil: 'Подтверди, прежде чем открыть личные сведения.',
  begin: 'Открыть мастерскую',
  wait: 'Подождать два хода',
  listen: 'Выслушать мастера: один ход',
  startA: 'Начать работу А',
  startB: 'Начать работу Б',
  nextPhase: 'Перейти к отдыху',
  finishShare: 'Поделиться результатом',
  finishKeep: 'Оставить результат',
  purchase: 'Купить образец без затраты хода',
  budget: 'Добавить один ход к запасу',
  slots: 'Места на полке',
  slot: 'Место {number}: {item}, возраст {age}',
  empty: 'пусто',
  'aegis.browser.select-item': 'Сначала выбери предмет.',
  occupied: 'Это место уже занято.',
  selected: 'Выбрано: {item}. Выбери пустое место.',
  cancelSelection: 'Отменить выбор',
  turns: 'Логический ход: {turn}. Осталось ходов: {remaining}.',
  produced: 'Готовых работ: {count}',
  credit: 'Запас монет: {count}',
  phase: 'Этап: {phase}',
  setup: 'подготовка',
  workshop: 'мастерская',
  rest: 'отдых',
  ready: 'готово',
  working: 'в работе',
  waiting: 'ожидает',
  incoming: 'ещё не пришёл',
  gone: 'ушёл',
  reader: 'Читатель',
  maker: 'Мастер',
  visitor: 'Гость',
  'batch-a': 'Работа А',
  'batch-b': 'Работа Б',
  shared: 'Результат подарен',
  kept: 'Результат сохранён',
  reloadConfig: 'Проверить новые правила для нового запуска',
  reloadWarning: 'Новые правила начнут игру заново после проверки. Сначала сохрани копию.',
  balanceReady: 'Новые правила работают в новом запуске.',
  ruleOrder: 'Порядок одного хода: работы, приход, уход.',
  status: 'Состояние',
  ambience: 'Включить тихий звуковой пример',
  silence: 'Тишина',
  print: 'Распечатать образец',
  generated: 'Созданный пример',
  printScope: 'Небольшие примеры одобренного содержания, а не полная настольная игра.',
};
